# Generated by Django 4.1.7 on 2023-03-20 20:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=99)),
                ('description', models.TextField()),
                ('closing_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('info', models.CharField(blank=True, max_length=199, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=99)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('matric_no', models.CharField(max_length=49)),
                ('school', models.CharField(max_length=199)),
                ('level', models.CharField(max_length=3)),
                ('department', models.CharField(max_length=199)),
                ('cgpa', models.CharField(max_length=4)),
                ('picture', models.ImageField(upload_to='profile_pic/')),
                ('admission_letter', models.FileField(upload_to='admission_letter/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('result', models.FileField(upload_to='result/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('national_identification', models.FileField(upload_to='national_id/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('id_card', models.FileField(upload_to='school_id/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholar.scholarship')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholar.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
